name: caesarpy
channels:
  - conda-forge
dependencies:
  # the basics
  - python<3.12
  - gdal
  - rasterio
  - matplotlib
  - scipy
  - pandas
  - geopandas
  - statsmodels
  # pre-processing
  - landlab
  # data visualisation
  - seaborn
  # notebook requires
  - jupyterlab
  - jupyterlab-spellchecker
  - voila
  - rise
  - ipywidgets
  - bokeh
  - nodejs
  - ipympl
  - jupyter_contrib_nbextensions
  # fancy visualisation requires
  - pyvista
  - ipygany
  - ipyvtklink
  # data stuff
  - xlrd
  - openpyxl
  # interpolation
  - verde
  # pip stuff
  - pip
  - pip:
      - richdem
      - pysheds
      - OWSLib


